# Generated by Django 4.0.5 on 2022-06-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADSBInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HexID', models.CharField(max_length=20)),
                ('Flag', models.CharField(max_length=20)),
                ('Callsign', models.CharField(max_length=20)),
                ('Registration', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=20)),
            ],
        ),
    ]
