# Generated by Django 4.0.5 on 2022-06-28 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_adsbinfo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsbinfo',
            name='photo',
        ),
        migrations.AddField(
            model_name='adsbinfo',
            name='img',
            field=models.ImageField(default='DefaultAircraft.png', upload_to='img/'),
        ),
    ]
