# Generated by Django 4.0.5 on 2022-06-28 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_adsbinfo_img_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Type',
            new_name='img_Type',
        ),
    ]
