# Generated by Django 4.0.5 on 2022-06-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_type_image_img_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsbinfo',
            name='img',
            field=models.ImageField(default='DefaultAircraft.png', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='adsbinfo',
            name='img_name',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
