# Generated by Django 4.0.5 on 2022-06-28 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_adsbinfo_img_alter_adsbinfo_img_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsbinfo',
            name='img_name',
        ),
    ]
