# Generated by Django 4.0.5 on 2022-06-30 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_adsbinfo_callsign_alter_adsbinfo_flag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADSBimg',
            fields=[
                ('Type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('img', models.ImageField(default='img/DefaultAircraft.png', null=True, upload_to='img/')),
            ],
        ),
    ]
