# Generated by Django 4.0.5 on 2022-06-30 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_adsbimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsbinfo',
            name='img',
        ),
    ]
