# Generated by Django 4.0.5 on 2022-11-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_adsbinfo_hexid'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsbinfo',
            name='Leixing',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
